% merged_data is generated by the script JDDscript_me_va
X = merged_data{1}; % X is a table, not an array
Xarray = X{:,:};
% Remove the mean for each odor (row)
Xarray_rm = Xarray - repmat(mean(Xarray,2),[1 size(Xarray,2)]);

% Scale each of the odors to "unit variance"
Xdot = sqrt(diag(Xarray_rm*Xarray_rm'));
Xarray_scaled = Xarray_rm./repmat(Xdot,[1 size(Xarray_rm,2)]);
X1 = X;
X1{:,:} = Xarray_scaled;


%[U,S,V] = svd(Xarray_scaled,'econ');
X1('diag_CO2(0.0)meTC',:) = [];
X1('diag_aphe(-5.0)meTC',:) = [];

indx = startsWith(X1.Properties.RowNames,'diag');
indxend = endsWith(X1.Properties.RowNames,'vaTC');
dvaArray = X1{indx & indxend,:};

indxmeTC = startsWith(X1.Properties.RowNames,'diag');
indxmeTC_end = endsWith(X1.Properties.RowNames,'meTC');

dmeArray = X1{indxmeTC & indxmeTC_end,:};

scaleFactor = 1.0;
shiftVal = 0.0;

dvaArray = dvaArray*scaleFactor;
dvaArray = dvaArray - repmat(shiftVal,size(dvaArray));

X1{indx & indxend,:} = dvaArray;

[U,S,V] = svd(X1{:,:},'econ');

A1 = dvaArray*V;
A2 = dmeArray*V;

Adiff = A1(:,1:3)-A2(:,1:3);

